channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.1
  - jupyterlab=4.1.1
  - matplotlib=3.8.2
  - numpy=1..26.4
  - pandas=2.2.0
  - seaborn=0.13.2
  - openpyxl=3.1.2
  - pip:
    - thefuzz==0.22.1
